= English Grammar Essentials

English gammar is, in essence, all about correctly transforming simple form of sentences and making sure components of sentences are synchronized in the process.
The transformation occurs when you want to make the simple sentence to be:

    * Negated
    * Questioned
    * Tensed
    * Composite Sentenced
    * Accompanied by auxilary verbs
    * Subjected by a Indefinite Pronoun
    * Passive
    * Imperative
    * Exclamative
    * Emphasized
    
You should be careful to syncrhonize following components when composing sentecnes:

    * Gender/Pluraility of Personal Pronouns
    * Article
    * Adjective/Adverb 


== Transformation
Let's start a two simple sentences each describing a state and a action:

```
 _The Universe is wide._ +
 _I observe the universe._
```

=== Negation
_The univers is not wide compared to the multiverse._
_I don't observe the universe any more._

=== Question

_Is the universe wide?_ +
_How wide is the universe?_ +
_Since when was the universe wide?_ +
_Do you observe the universe?_
_

=== Tensed
_The universe was wide._ +
_The universe will be wide._ +
_The universe has been wide from the beginning._ +
_The universe had been wide back then too._ +
_I am observing the universe._ +
_I will be observing the universe._ +

=== Composite Sentenced
_I know that the universe is wide._ +
_I know how wide the universe is._ +

=== Accompanied by auxilary verbs
_The universe may be an illusion._ +
_I can observe the universe at nights._ +
_I have to observe the universe all the time._ +
_I must observe the universe all the time._ +
_I should observe the universe all the time._ +


   
   
   
   
    * Subjected by a Indefinite Pronoun
    * Passive
    * Imperative
    * Exclamative
    * Emphasized
