= English Grammar Essentials

English gammar is, in essence, all about correctly transforming simple form of sentences and making sure components of sentences are synchronized in the process.
The transformation occurs when you want to make the simple sentence to be:

    * Negated
    * Questioned
    * Tensed
    * Composite Sentenced
    * Accompanied by auxilary verbs
    * Subjected by a Indefinite Pronoun
    * Passive
    * Imperative
    * Exclamative
    * Emphasized
    
You should be careful to syncrhonize following components when composing sentecnes:

    * Gender/Pluraility of Personal Pronouns
    * Article
    * Adjective/Adverb 


== Transformation
Let's start a two simple sentences each describing a state and a action:

----
 The Universe is wide.
 I observe the universe.
----

=== Negation
_The univers is not wide compared to the multiverse._
_I don't observe the universe any more._

=== Question
_Is the universe wide?_ +
_How wide is the universe?_ +
_Since when was the universe wide?_ +
_Do you observe the universe?_
_

=== Tensed
_The universe was wide._ +
_The universe will be wide._ +
_The universe has been wide from the beginning._ +
_The universe had been wide back then too._ +
_I am observing the universe._ +
_I will be observing the universe._ +

_I observed the universe all the time._ +
_I drank a coffee observing the universe._

=== Composite Sentenced
_I know that the universe is wide._ +
_I know how wide the universe is._ +

=== Accompanied by auxilary verbs
_The universe may be an illusion._ +
_I can observe the universe at nights._ +
_I have to observe the universe all the time._ +
_I must observe the universe all the time._ +
_I should observe the universe all the time._ +

=== Subjected by a Indefinite Pronoun
_It is said that the uiverse is wide._ +
_It rainde when I was observing the universe._

=== Passive
_The universe is said to be wide._ +
_The universe will be thoroughly observed by me._

=== Imperative
_Be wide, Universe!_ +
_Observe the universe._

=== Exclamative
_What a wide universe!_ +
_What a careful observer you are!_

=== Emphasized
_Widest is the Universe._

=== Conditional
_If the universe was smaller, start could not have been born._ +
_If I had observed the universe harder in middle shcool, I could have become a greater scholar._


== Syncrhonization
The bold parts of a sentence should be consistent in following points:

=== Gender/Pluraility of Personal Pronouns
The *Universe* *is* wide. +
The *Multiverses* **are** wide. 

*I* *am* observant. +
*You* *are* observant. +
*He* *is* observant. +
[underline]#They# **are** observant.

There are *many* universe**s**. +
I spent *countless* night**s** observing the universe.

=== Article
I ate *a* pear. +
I ate *an* orange. +

Do you observe *the* Universe? +
*The* Sun and *the* Moon +
*The* United States of America +
Korea +
*The* Republic of Korea +
*The* Simpsons

=== Adjective/Adverb 
The universe is so *beautifull*. +
The universe is *beautifully* designed.
